cluster.name: docker-cluster
network.host: 0.0.0.0
xpack.license.self_generated.type: basic
xpack.security.enabled: true

xpack.security.http.ssl:
  enabled: true
  key: certs/elasticsearch/elasticsearch.key
  certificate: certs/elasticsearch/elasticsearch.crt
  certificate_authorities: certs/ca/ca.crt

xpack.security.transport.ssl:
  enabled: true
  key: certs/elasticsearch/elasticsearch.key
  certificate: certs/elasticsearch/elasticsearch.crt
  certificate_authorities: certs/ca/ca.crt